from enum import Enum


class TriggerType(str, Enum):
    """
    The TriggerType class is an Enum class that defines the trigger types for a given request.
    It indicates the type of trigger that initiated the request.
    "auto" - The trigger was automatically generated.
    "man" - The trigger was manually generated (e.g., by a user using ctrl+space).
    "idle" - The trigger was generated by the IDE when the user is idle (e.g., after a certain time of inactivity).
    """
    auto    = "auto"
    man     = "man"
    idle    = "idle"


class IDEType(str, Enum):
    """
    The IDEType class is an Enum class that defines the IDE types for a given request.
    It indicates the IDE in which the code snippet is being written.
    """
    # TODO: decide whether it should be JetBrains collectively or each IDE separately
    # -Aral (4 Jul): I think let's collect what we can collect, so each IDE separately
    vscode = "vscode"
    jetbrains = "jetbrains"


class LanguageType(str, Enum):
    """
    The LanguageType class is an Enum class that defines the language types for a given request.
    It indicates the programming language of the code snippet for which the completion is requested.
    """
    # TODO: adhere to the types as provided by the vsc api
    # -Aral (4 Jul): We will need to refactor this code (all models sent on 
    # the network) to also be included on the client-side plugin somehow
    py = "py"
    js = "js"
    java = "java"
    cpp = "cpp"
    c = "c"
    swift = "swift"
    php = "php"
    go = "go"
    rb = "rb"
    cs = "cs"
    kt = "kt"
